Repository egouldo/ManyAnalysts, pull requests merged in 2024-08, with the labels that each got.

#71 fix for quarto cross-reference not rendering
  supp_mat/SM3_ExplainingDeviation.qmd
Labels: bug, Quarto

#75 Update to latest ManyEcoEvo and ensure #50 cross-refs render
  .Rprofile
  _freeze/index/execute-results/html.json
  _freeze/supp_mat/SM1_summary/execute-results/html.json
  _freeze/supp_mat/SM2_EffectSizeAnalysis/execute-results/html.json
  _freeze/supp_mat/SM2_EffectSizeAnalysis/figure-html/fig-euc-yi-forest-plot-full-1.png
  _quarto.yml
  index.qmd
  renv.lock
  supp_mat/SM1_summary.qmd
  supp_mat/SM2_EffectSizeAnalysis.qmd
  supp_mat/SM3_ExplainingDeviation.qmd
  supp_mat/SM3_ExplainingDeviation_files/figure-html/fig-box-cox-transformations-1.png
  supp_mat/SM3_ExplainingDeviation_files/figure-html/fig-effects-plots-BT-1.png
  supp_mat/SM3_ExplainingDeviation_files/figure-html/fig-effects-plots-Euc-1.png
  supp_mat/SM3_ExplainingDeviation_files/figure-html/fig-yi-deviation-cont-rating-1.png
  supp_mat/SM3_ExplainingDeviation_files/figure-html/fig-yi-euc-deviation-RE-plots-1.png
  supp_mat/SM4_case_study_datasets.qmd
  utils.R
Labels: Quarto, breaking change :skull_and_crossbones:, upkeep

#66 Fix table C3
  supp_mat/SM3_ExplainingDeviation.qmd
Labels: bug
